// functions/submit.js
const PDFDocument = require('pdfkit');
const nodemailer = require('nodemailer');

/**
 * Helper to convert dataURL to Buffer
 */
function dataURLtoBuffer(dataURL) {
  const matches = dataURL.match(/^data:(image\/\w+);base64,(.+)$/);
  if (!matches) throw new Error('Invalid dataURL');
  return Buffer.from(matches[2], 'base64');
}

/**
 * Generate PDF buffer from submitted data
 */
function generatePdfBuffer(form) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 40 });
      const buffers = [];
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => resolve(Buffer.concat(buffers)));

      // Header
      doc.fontSize(16).text('Site Visit Monitoring Sheet', { align: 'center' });
      doc.moveDown();

      // Key fields
      doc.fontSize(11);
      doc.text('Employee Name: ' + (form.employeeName || ''));
      doc.moveDown(0.4);
      doc.text('In Date: ' + (form.inDate || ''));
      doc.moveDown(0.4);
      doc.text('Out Date: ' + (form.outDate || ''));
      doc.moveDown(0.4);
      doc.text('Site / Location: ' + (form.siteLocation || ''));
      doc.moveDown(0.6);
      doc.text('Purpose of Visit / Work Description:');
      doc.font('Helvetica').fontSize(10).text(form.purpose || '', { indent: 10 });
      doc.moveDown(0.8);

      doc.fontSize(11).font('Helvetica-Bold').text('Supervisor Details');
      doc.font('Helvetica').fontSize(11).text('Supervisor Name: ' + (form.supervisorName || ''));
      doc.moveDown(0.4);

      // Signatures area
      doc.fontSize(11).text('Supervisor Signature:');
      if (form.supervisorSig) {
        const supBuf = dataURLtoBuffer(form.supervisorSig);
        doc.image(supBuf, { fit: [250, 80] });
        doc.moveDown(1);
      } else {
        doc.moveDown(2);
      }

      doc.fontSize(11).text('Employee Signature:');
      if (form.employeeSig) {
        const empBuf = dataURLtoBuffer(form.employeeSig);
        doc.image(empBuf, { fit: [250, 80] });
        doc.moveDown(1);
      } else {
        doc.moveDown(2);
      }

      doc.fontSize(11).text('Remarks:');
      doc.fontSize(10).text(form.remarks || '', { indent: 10 });
      doc.moveDown(1);

      doc.fontSize(9).text('This PDF was auto-generated by Site Visit Monitoring Form.', { align: 'center' });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

/**
 * Lambda handler
 */
exports.handler = async function(event, context) {
  try {
    if (event.httpMethod !== 'POST') {
      return { statusCode: 405, body: JSON.stringify({ error: 'Method not allowed' }) };
    }
    const body = JSON.parse(event.body || '{}');

    // Basic validation
    if (!body.employeeName || !body.supervisorName) {
      return { statusCode: 400, body: JSON.stringify({ error: 'Missing required fields' }) };
    }

    // generate PDF
    const pdfBuffer = await generatePdfBuffer(body);

    // Prepare mail transport - reads credentials from env
    const SMTP_HOST = process.env.SMTP_HOST;
    const SMTP_PORT = process.env.SMTP_PORT || 587;
    const SMTP_USER = process.env.SMTP_USER;
    const SMTP_PASS = process.env.SMTP_PASS;
    const FROM_EMAIL = process.env.FROM_EMAIL || SMTP_USER;
    const TO_EMAIL = process.env.TO_EMAIL || 'hr.himani@goelequipments.com';

    if (!SMTP_HOST || !SMTP_USER || !SMTP_PASS) {
      console.error('Missing SMTP env vars');
      return { statusCode: 500, body: JSON.stringify({ error: 'SMTP not configured on server' }) };
    }

    const transporter = nodemailer.createTransport({
      host: SMTP_HOST,
      port: parseInt(SMTP_PORT, 10),
      secure: SMTP_PORT == 465,
      auth: {
        user: SMTP_USER,
        pass: SMTP_PASS
      }
    });

    const mailOptions = {
      from: FROM_EMAIL,
      to: TO_EMAIL,
      subject: `Site Visit Form: ${body.employeeName} - ${body.siteLocation || ''}`,
      text: `Site visit submission from ${body.employeeName}\n\nPlease find attached PDF.`,
      attachments: [{
        filename: `site-visit-${(body.employeeName || 'unknown').replace(/\\s+/g,'_')}.pdf`,
        content: pdfBuffer,
        contentType: 'application/pdf'
      }]
    };

    await transporter.sendMail(mailOptions);

    return {
      statusCode: 200,
      body: JSON.stringify({ ok: true, message: 'Email sent' })
    };

  } catch (err) {
    console.error('Function error', err);
    return {
      statusCode: 500,
      body: JSON.stringify({ error: err.message || 'Server error' })
    };
  }
};
